//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5420
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XizheC.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://oyxxi.com/", ConfigurationName="ServiceReference1.Service1Soap")]
    public interface Service1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://oyxxi.com/getsqlcon", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string getsqlcon(string USER_NAME, string PASSWORD, string DOMAIN);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface Service1SoapChannel : XizheC.ServiceReference1.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<XizheC.ServiceReference1.Service1Soap>, XizheC.ServiceReference1.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getsqlcon(string USER_NAME, string PASSWORD, string DOMAIN) {
            return base.Channel.getsqlcon(USER_NAME, PASSWORD, DOMAIN);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://oyxxi.com/", ConfigurationName="ServiceReference1.Service1HttpGet")]
    public interface Service1HttpGet {
        
        // CODEGEN: 操作 getsqlcon 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://oyxxi.com/Service1HttpGet/getsqlconRequest", ReplyAction="http://oyxxi.com/Service1HttpGet/getsqlconResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        XizheC.ServiceReference1.getsqlconResponse getsqlcon(XizheC.ServiceReference1.getsqlconRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getsqlconRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string USER_NAME;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string PASSWORD;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string DOMAIN;
        
        public getsqlconRequest() {
        }
        
        public getsqlconRequest(string USER_NAME, string PASSWORD, string DOMAIN) {
            this.USER_NAME = USER_NAME;
            this.PASSWORD = PASSWORD;
            this.DOMAIN = DOMAIN;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getsqlconResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://oyxxi.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @string;
        
        public getsqlconResponse() {
        }
        
        public getsqlconResponse(string @string) {
            this.@string = @string;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface Service1HttpGetChannel : XizheC.ServiceReference1.Service1HttpGet, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class Service1HttpGetClient : System.ServiceModel.ClientBase<XizheC.ServiceReference1.Service1HttpGet>, XizheC.ServiceReference1.Service1HttpGet {
        
        public Service1HttpGetClient() {
        }
        
        public Service1HttpGetClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1HttpGetClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1HttpGetClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1HttpGetClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        XizheC.ServiceReference1.getsqlconResponse XizheC.ServiceReference1.Service1HttpGet.getsqlcon(XizheC.ServiceReference1.getsqlconRequest request) {
            return base.Channel.getsqlcon(request);
        }
        
        public string getsqlcon(string USER_NAME, string PASSWORD, string DOMAIN) {
            XizheC.ServiceReference1.getsqlconRequest inValue = new XizheC.ServiceReference1.getsqlconRequest();
            inValue.USER_NAME = USER_NAME;
            inValue.PASSWORD = PASSWORD;
            inValue.DOMAIN = DOMAIN;
            XizheC.ServiceReference1.getsqlconResponse retVal = ((XizheC.ServiceReference1.Service1HttpGet)(this)).getsqlcon(inValue);
            return retVal.@string;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://oyxxi.com/", ConfigurationName="ServiceReference1.Service1HttpPost")]
    public interface Service1HttpPost {
        
        // CODEGEN: 操作 getsqlcon 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://oyxxi.com/Service1HttpPost/getsqlconRequest", ReplyAction="http://oyxxi.com/Service1HttpPost/getsqlconResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        XizheC.ServiceReference1.getsqlconResponse1 getsqlcon(XizheC.ServiceReference1.getsqlconRequest1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getsqlconRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string USER_NAME;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string PASSWORD;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string DOMAIN;
        
        public getsqlconRequest1() {
        }
        
        public getsqlconRequest1(string USER_NAME, string PASSWORD, string DOMAIN) {
            this.USER_NAME = USER_NAME;
            this.PASSWORD = PASSWORD;
            this.DOMAIN = DOMAIN;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getsqlconResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://oyxxi.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @string;
        
        public getsqlconResponse1() {
        }
        
        public getsqlconResponse1(string @string) {
            this.@string = @string;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface Service1HttpPostChannel : XizheC.ServiceReference1.Service1HttpPost, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class Service1HttpPostClient : System.ServiceModel.ClientBase<XizheC.ServiceReference1.Service1HttpPost>, XizheC.ServiceReference1.Service1HttpPost {
        
        public Service1HttpPostClient() {
        }
        
        public Service1HttpPostClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1HttpPostClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1HttpPostClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1HttpPostClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        XizheC.ServiceReference1.getsqlconResponse1 XizheC.ServiceReference1.Service1HttpPost.getsqlcon(XizheC.ServiceReference1.getsqlconRequest1 request) {
            return base.Channel.getsqlcon(request);
        }
        
        public string getsqlcon(string USER_NAME, string PASSWORD, string DOMAIN) {
            XizheC.ServiceReference1.getsqlconRequest1 inValue = new XizheC.ServiceReference1.getsqlconRequest1();
            inValue.USER_NAME = USER_NAME;
            inValue.PASSWORD = PASSWORD;
            inValue.DOMAIN = DOMAIN;
            XizheC.ServiceReference1.getsqlconResponse1 retVal = ((XizheC.ServiceReference1.Service1HttpPost)(this)).getsqlcon(inValue);
            return retVal.@string;
        }
    }
}
